import {useEffect,useMemo,useState} from 'react';import {buildHttpRequest,Method} from '../lib/requestBuilder';import {CodeBlock} from './CodeBlock';
export function ClientQuestion(){const [a,setA]=useState('');return <div className="card"><p className="font-semibold">ServiceA calls Serviceb. What is ServiceA?</p>{['Server','Client','Database','Proxy'].map(o=><button className="m-1 rounded-lg border px-3 py-2 hover:bg-blue-50" onClick={()=>setA(o)} key={o}>{o}</button>)}{a&&<p className={a==='Client'?'text-green-700':'text-red-700'}>{a==='Client'?'Correct: ServiceA initiates this request.':'Not quite. ServiceA is the client for the Serviceb call.'}</p>}</div>}
export function HttpHighlighter(){const [part,setPart]=useState('GET');const map:Record<string,string>={GET:'HTTP method: action to read a resource.',URL:'URL/path: /orders/ORD123 identifies the resource.',Header:'Headers: Host and Authorization carry metadata.','Query parameter':'status=PENDING filters or modifies the request.','Path parameter':'ORD123 is the order id path value.'};return <div><div className="grid gap-2 sm:grid-cols-5">{Object.keys(map).map(x=><button className={`rounded-lg border p-2 ${part===x?'bg-yellow-100 border-yellow-500':''}`} onClick={()=>setPart(x)}>{x}</button>)}</div><CodeBlock code={'GET /orders/ORD123?status=PENDING HTTP/1.1\nHost: example.com\nAuthorization: Bearer xxx'}/><p className="rounded-lg bg-yellow-50 p-3">{map[part]}</p></div>}
export function RequestBuilder(){const [method,setMethod]=useState<Method>('GET'),[path,setPath]=useState('/orders/ORD123'),[query,setQuery]=useState('status=PENDING'),[header,setHeader]=useState('Authorization: Bearer xxx'),[body,setBody]=useState('');return <div className="grid gap-3"><select value={method} onChange={e=>setMethod(e.target.value as Method)} className="rounded border p-2">{['GET','POST','PUT','PATCH','DELETE'].map(m=><option>{m}</option>)}</select><input value={path} onChange={e=>setPath(e.target.value)} className="rounded border p-2" placeholder="Path"/><input value={query} onChange={e=>setQuery(e.target.value)} className="rounded border p-2" placeholder="Query parameter"/><input value={header} onChange={e=>setHeader(e.target.value)} className="rounded border p-2" placeholder="Header"/><textarea value={body} onChange={e=>setBody(e.target.value)} className="rounded border p-2" placeholder="Body"/><CodeBlock code={buildHttpRequest(method,path,query,header,body)}/></div>}
export function StatusQuiz(){const [a,setA]=useState('');return <div><p className="font-semibold">Your service cannot find the requested order. Which response is appropriate?</p>{['200','400','404','500'].map(o=><button onClick={()=>setA(o)} className="m-1 rounded border px-3 py-2">{o}</button>)}{a&&<p className={a==='404'?'text-green-700':'text-red-700'}>{a==='404'?'Correct: use 404 Not Found.':'Incorrect. Missing resource maps to 404.'}</p>}</div>}
export const StaticDiagram=({items}:{items:string[]})=><div className="my-4 flex flex-wrap items-center gap-2">{items.map((i,n)=><span className="rounded-xl bg-white p-3 shadow" key={i}>{i}{n<items.length-1&&<b> ↓</b>}</span>)}</div>;
export function DispatcherExercise(){const [a,setA]=useState('');return <div><CodeBlock code={'@GetMapping("/orders/{orderId}")\nGET /orders/ORD123'}/><p>Which controller method handles this request?</p>{['getOrder(String orderId)','createOrder(Request body)','cancelOrder(String orderId)'].map(o=><button className="m-1 rounded border p-2" onClick={()=>setA(o)}>{o}</button>)}{a&&<p>{a.startsWith('getOrder')?'Correct.':'The mapping selects getOrder(String orderId).'}</p>}</div>}
export function MatchingGame(){return <div className="grid gap-2 sm:grid-cols-3">{['@PathVariable → /orders/{orderId}','@RequestParam → ?status=PENDING','@RequestBody → JSON body'].map(x=><div className="rounded-xl bg-green-50 p-3">{x}</div>)}</div>}
export function Lifecycle(){const nodes=['Client','HTTP Request','Tomcat','Servlet','DispatcherServlet','HandlerMapping','Controller','Service','Repository','Database','Response','Client'];const [active,setActive]=useState(0),[play,setPlay]=useState(false);useEffect(()=>{if(!play)return;const id=setInterval(()=>setActive(x=>x<nodes.length-1?x+1:0),900);return()=>clearInterval(id)},[play]);return <div><div className="mb-4 flex gap-2"><button className="rounded bg-blue-600 px-4 py-2 text-white" onClick={()=>setPlay(!play)}>{play?'Pause':'Play Animation'}</button><button className="rounded border px-4 py-2" onClick={()=>{setPlay(false);setActive(0)}}>Reset</button></div><div className="grid gap-2 sm:grid-cols-3">{nodes.map((n,i)=><button className={`node rounded-xl border p-4 ${active===i?'bg-blue-600 text-white scale-105':'bg-white'}`} onClick={()=>setActive(i)}>{n}</button>)}</div><p className="mt-4 rounded-xl bg-blue-50 p-4"><b>{nodes[active]}:</b> {explain(nodes[active])}</p></div>}
function explain(n:string){return ({Client:'Starts the request and receives the response.','HTTP Request':'Protocol message with method, URL, headers and optional body.',Tomcat:'Servlet container that accepts the connection.',Servlet:'Java web component model.',DispatcherServlet:'Spring MVC front controller.',HandlerMapping:'Finds the matching handler method.',Controller:'HTTP-facing application method.',Service:'Business logic layer.',Repository:'Persistence abstraction.',Database:'Stores data for the application.',Response:'Status, headers and optional body returned to the client.'} as Record<string,string>)[n]}
